# Generated by Django 2.1.4 on 2018-12-23 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 15, 44, 23, 242930)),
        ),
    ]
