# Generated by Django 2.1.4 on 2018-12-28 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tw_auth', '0003_auto_20181228_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=24)),
                ('browser', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('unauthorized', models.BooleanField(default=False)),
            ],
        ),
    ]
