# Generated by Django 2.0.1 on 2018-12-27 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw_auth', '0004_auto_20181227_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 18, 57, 21, 460541)),
        ),
    ]
