# Generated by Django 2.0.1 on 2018-12-28 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tw_auth', '0005_auto_20181227_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 12, 31, 59, 661869)),
        ),
    ]
